"""empty message

Revision ID: 90acb6e7a479
Revises: 
Create Date: 2022-03-21 16:09:50.853145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90acb6e7a479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('bedrooms', sa.String(length=80), nullable=True),
    sa.Column('bathrooms', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('property_type', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Properties')
    # ### end Alembic commands ###
